# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install Dependencies
      run: |
        pipenv install
    - name: List files for debugging
      run: |
          echo "GITHUB_WORKSPACE:" ${GITHUB_WORKSPACE}
          echo "PWD:" ${PWD}
          ls -al
          tree .
    - name: Test with pytest
      run: |
        python -m pytest

  static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install Dependencies
      run: |
        pipenv install
    - name: Generate the static pages
      run: |
        generate-schema-doc schemas/identifier_schema.json ./static/identifier
